-- Generated by csv-to-sql.ts

-- Clear existing commercial entries before re-import
DELETE FROM personal_entries WHERE rakija_id IN (SELECT id FROM rakija WHERE type = 'commercial');
DELETE FROM rakija WHERE type = 'commercial';

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Пещерска гроздова ракия', 'Винпром Пещера', 'grape', 'Пещера', 'Bulgaria', 40, NULL, 'Гроздова ракия. Класическа марка', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Пещерска мускатова ракия', 'Винпром Пещера', 'grape', 'Пещера', 'Bulgaria', 40, NULL, 'Мускатова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кайлъшка гроздова ракия', 'Винпром Пещера', 'grape', 'Пещера', 'Bulgaria', 40, NULL, 'Гроздова ракия. По рецепта от Плевен', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кайлъшка мускатова ракия', 'Винпром Пещера', 'grape', 'Пещера', 'Bulgaria', 40, NULL, 'Мускатова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кайлъшка сливова ракия', 'Винпром Пещера', 'plum', 'Пещера', 'Bulgaria', 40, NULL, 'Сливова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Стралджанска мускатова', 'Винпром Пещера', 'grape', 'Пещера', 'Bulgaria', 40, NULL, 'Мускатова ракия. ЗГУ', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Стралджанска мускатова Барел', 'Винпром Пещера', 'grape', 'Пещера', 'Bulgaria', 40, NULL, 'Мускатова ракия отлежала. Бъчва', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Мастика Пещера', 'Винпром Пещера', 'other', 'Пещера', 'Bulgaria', 40, NULL, 'Мастика. Лидер в категорията', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Мента Пещера', 'Винпром Пещера', 'other', 'Пещера', 'Bulgaria', 40, NULL, 'Мента (зелена). Лидер в категорията', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Водка Flirt', 'Винпром Пещера', 'other', 'Пещера', 'Bulgaria', 40, NULL, 'Водка. Лидер в категорията', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Водка Аляска', 'Винпром Пещера', 'other', 'Пещера', 'Bulgaria', 40, NULL, 'Водка', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Black Ram Whisky', 'Винпром Пещера', 'other', 'Пещера', 'Bulgaria', 40, NULL, 'Уиски. Българско уиски', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Sixth Sense Gin', 'Винпром Пещера', 'other', 'Пещера', 'Bulgaria', 40, NULL, 'Джин', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Карнобатска гроздова ракия', 'SIS Industries (Винпром Карнобат)', 'grape', 'Карнобат', 'Bulgaria', 40, NULL, 'Гроздова ракия. ЗГУ', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Карнобатска мускатова ракия', 'SIS Industries (Винпром Карнобат)', 'grape', 'Карнобат', 'Bulgaria', 40, NULL, 'Мускатова ракия. Сорт Мускат Отонел', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кехлибар (стандарт)', 'SIS Industries (Винпром Карнобат)', 'grape', 'Карнобат', 'Bulgaria', 40, NULL, 'Гроздова ракия. Отлежала с кехлибар', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кехлибар Резерва', 'SIS Industries (Винпром Карнобат)', 'grape', 'Карнобат', 'Bulgaria', 40, NULL, 'Гроздова ракия отлежала. 3 г. дъбови бъчви', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Мастика Карнобат', 'SIS Industries (Винпром Карнобат)', 'other', 'Карнобат', 'Bulgaria', 40, NULL, 'Мастика', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Узо Zorbas (Зорбас)', 'SIS Industries (Винпром Карнобат)', 'other', 'Карнобат', 'Bulgaria', 40, NULL, 'Узо. Гръцки стил', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Водка Savoy', 'SIS Industries (Винпром Карнобат)', 'other', 'Карнобат', 'Bulgaria', 40, NULL, 'Водка. Зърнен алкохол', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Водка Savoy Silver', 'SIS Industries (Винпром Карнобат)', 'other', 'Карнобат', 'Bulgaria', 40, NULL, 'Водка премиум. Многоетапна филтрация', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Текила Savoy', 'SIS Industries (Винпром Карнобат)', 'other', 'Карнобат', 'Bulgaria', 40, NULL, 'Текила. Дестилирана в Мексико', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Mary Jane (водка/коктейли)', 'SIS Industries (Винпром Карнобат)', 'other', 'Карнобат', 'Bulgaria', 40, NULL, 'Водка / RTD коктейли. Бранд за млади', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Bubbles', 'SIS Industries (Винпром Карнобат)', 'other', 'Карнобат', 'Bulgaria', 40, NULL, 'Шумящи напитки / RTD', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Ethno', 'SIS Industries (Винпром Карнобат)', 'other', 'Карнобат', 'Bulgaria', 40, NULL, 'Ракия / спиртни. Етно линия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Троянска сливова ракия (стандарт)', 'Винпром Троян', 'plum', 'Троян', 'Bulgaria', 40, NULL, 'Сливова ракия. ЗГУ', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Стара Троянска сливова ракия', 'Винпром Троян', 'plum', 'Троян', 'Bulgaria', 40, NULL, 'Сливова ракия отлежала. Дъбови бъчви', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Слънчева сливова ракия', 'Винпром Троян', 'plum', 'Троян', 'Bulgaria', 40, NULL, 'Сливова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Троянска сливова Резерва 18 г.', 'Винпром Троян', 'plum', 'Троян', 'Bulgaria', 40, NULL, 'Сливова ракия отлежала. 18 г. в дъб', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Троянска сливова Специална Резерва 25 г.', 'Винпром Троян', 'plum', 'Троян', 'Bulgaria', 40, NULL, 'Сливова ракия премиум. 25+ г. отлежаване', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Троянска Златна Резерва', 'Винпром Троян', 'plum', 'Троян', 'Bulgaria', 40, NULL, 'Сливова ракия премиум. 43% алк.', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Сливова - Сингъл Барел', 'Винпром Троян', 'plum', 'Троян', 'Bulgaria', 40, NULL, 'Сливова ракия колекционерска. Една бъчва от 1989', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кайсиева ракия', 'Винпром Троян', 'apricot', 'Троян', 'Bulgaria', 40, NULL, 'Плодова ракия. Кайсии', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Стара кайсиева ракия', 'Винпром Троян', 'apricot', 'Троян', 'Bulgaria', 40, NULL, 'Плодова ракия отлежала. 5 г. в дъбови бъчви', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Ябълкова ракия', 'Винпром Троян', 'other', 'Троян', 'Bulgaria', 40, NULL, 'Плодова ракия. Ябълки', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Черешова ракия', 'Винпром Троян', 'other', 'Троян', 'Bulgaria', 40, NULL, 'Плодова ракия. Череши', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Крушова ракия (Williams)', 'Винпром Троян', 'pear', 'Троян', 'Bulgaria', 40, NULL, 'Плодова ракия. Сорт Williams', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Дюлева ракия', 'Винпром Троян', 'quince', 'Троян', 'Bulgaria', 40, NULL, 'Плодова ракия. Дюли', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Билкова ракия', 'Винпром Троян', 'grape', 'Троян', 'Bulgaria', 40, NULL, 'Билкова ракия. Билков купаж', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Греяна ракия', 'Винпром Троян', 'grape', 'Троян', 'Bulgaria', 40, NULL, 'Греяна ракия. Подсладена', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Мозер (карафа)', 'Винпром Троян', 'grape', 'Троян', 'Bulgaria', 40, NULL, 'Премиум серия. Кристална карафа', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Taskov гроздова ракия', 'Винпром-Тасков', 'grape', 'Стара Загора', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Taskov мускатова', 'Винпром-Тасков', 'grape', 'Стара Загора', 'Bulgaria', 40, NULL, 'Мускатова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Taskov сливова', 'Винпром-Тасков', 'plum', 'Стара Загора', 'Bulgaria', 40, NULL, 'Сливова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Taskov бренди', 'Винпром-Тасков', 'grape', 'Стара Загора', 'Bulgaria', 40, NULL, 'Бренди', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Taskov ликьори', 'Винпром-Тасков', 'other', 'Стара Загора', 'Bulgaria', 40, NULL, 'Ликьор. Различни вкусове', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кюстендилска гроздова ракия', 'Винпром Кюстендил', 'grape', 'Кюстендил', 'Bulgaria', 40, NULL, 'Гроздова ракия. 40% алк.', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кюстендилска ябълкова ракия', 'Винпром Кюстендил', 'other', 'Кюстендил', 'Bulgaria', 40, NULL, 'Плодова ракия. Кюстендилски ябълки', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кюстендилска вилямова ракия', 'Винпром Кюстендил', 'pear', 'Кюстендил', 'Bulgaria', 40, NULL, 'Плодова ракия (круша). Сорт Вилямова масловка', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кюстендилска черешова ракия', 'Винпром Кюстендил', 'other', 'Кюстендил', 'Bulgaria', 40, NULL, 'Плодова ракия. Череши', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кюстендилска сливова ракия', 'Винпром Кюстендил', 'plum', 'Кюстендил', 'Bulgaria', 40, NULL, 'Сливова ракия. Златисто-кафяв цвят', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Моминска гроздова ракия', 'Винпром Кюстендил', 'grape', 'Кюстендил', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Момински ликьор Портокал', 'Винпром Кюстендил', 'other', 'Кюстендил', 'Bulgaria', 40, NULL, 'Ликьор. Портокал', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Кралско бренди', 'Винпром Кюстендил', 'grape', 'Кюстендил', 'Bulgaria', 40, NULL, 'Бренди', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Джин кралски', 'Винпром Кюстендил', 'other', 'Кюстендил', 'Bulgaria', 40, NULL, 'Джин', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Мастика', 'Винпром Кюстендил', 'other', 'Кюстендил', 'Bulgaria', 40, NULL, 'Мастика', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Highlander уиски (кен)', 'Винпром Кюстендил', 'other', 'Кюстендил', 'Bulgaria', 40, NULL, 'Уиски', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Дупнишка гроздова ракия', 'Винпром-Дупница', 'grape', 'Дупница', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Дупнишка мускатова', 'Винпром-Дупница', 'grape', 'Дупница', 'Bulgaria', 40, NULL, 'Мускатова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Дупнишка сливова', 'Винпром-Дупница', 'plum', 'Дупница', 'Bulgaria', 40, NULL, 'Сливова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Бренди Дупница', 'Винпром-Дупница', 'grape', 'Дупница', 'Bulgaria', 40, NULL, 'Бренди', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Гроздови ракии (различни марки)', 'Нордикс', 'grape', 'София', 'Bulgaria', 40, NULL, 'Гроздова ракия. Бутилиране', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Водка', 'Нордикс', 'other', 'София', 'Bulgaria', 40, NULL, 'Водка', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Ликьори', 'Нордикс', 'other', 'София', 'Bulgaria', 40, NULL, 'Ликьор', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Гроздови ракии', 'Докторс', 'grape', 'Пловдив', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Плодови ракии', 'Докторс', 'mixed', 'Пловдив', 'Bulgaria', 40, NULL, 'Плодова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Водка', 'Докторс', 'other', 'Пловдив', 'Bulgaria', 40, NULL, 'Водка', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Джин', 'Докторс', 'other', 'Пловдив', 'Bulgaria', 40, NULL, 'Джин', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Ликьори', 'Докторс', 'other', 'Пловдив', 'Bulgaria', 40, NULL, 'Ликьор', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Гроздови ракии', 'Синхрон Инвест', 'grape', 'София', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Водки', 'Синхрон Инвест', 'other', 'София', 'Bulgaria', 40, NULL, 'Водка', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Джин', 'Синхрон Инвест', 'other', 'София', 'Bulgaria', 40, NULL, 'Джин', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Ликьори', 'Синхрон Инвест', 'other', 'София', 'Bulgaria', 40, NULL, 'Ликьор', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Гроздови ракии', 'Бонидекс', 'grape', 'Сливен', 'Bulgaria', 40, NULL, 'Гроздова ракия. Сливен', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Плодови ракии', 'Бонидекс', 'mixed', 'Сливен', 'Bulgaria', 40, NULL, 'Плодова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Ликьори', 'Бонидекс', 'other', 'Сливен', 'Bulgaria', 40, NULL, 'Ликьор', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Бургас 63', 'Винпром Бургас', 'grape', 'Бургас', 'Bulgaria', 40, NULL, 'Гроздова ракия. Емблематична марка от 1963', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Бургаска мускатова', 'Винпром Бургас', 'grape', 'Бургас', 'Bulgaria', 40, NULL, 'Мускатова ракия. ЗГУ', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Бургаска специална', 'Винпром Бургас', 'grape', 'Бургас', 'Bulgaria', 40, NULL, 'Гроздова ракия отлежала', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Ликьори Бургас', 'Винпром Бургас', 'other', 'Бургас', 'Bulgaria', 40, NULL, 'Ликьор. Различни вкусове', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Сливенска перла', 'Винпром Сливен', 'grape', 'Сливен', 'Bulgaria', 40, NULL, 'Гроздова ракия. Премиум, сорт Перла', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Сливенска гроздова', 'Винпром Сливен', 'grape', 'Сливен', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Сливенска мускатова', 'Винпром Сливен', 'grape', 'Сливен', 'Bulgaria', 40, NULL, 'Мускатова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Стара Соколова 12 Лукс', 'Винпром Сливен', 'plum', 'Сливен', 'Bulgaria', 40, NULL, 'Сливова ракия премиум. 12 г. отлежала, тройна дестилация', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Тетевенска сливова ракия', 'Винпром Тетевен', 'plum', 'Тетевен', 'Bulgaria', 40, NULL, 'Сливова ракия. ЗГУ', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Стара тетевенска сливова', 'Винпром Тетевен', 'plum', 'Тетевен', 'Bulgaria', 40, NULL, 'Сливова ракия отлежала', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Поморийска гроздова ракия', 'Черноморско злато (Винпром Поморие)', 'grape', 'Поморие', 'Bulgaria', 40, NULL, 'Гроздова ракия. ЗГУ', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Поморийско бренди (3,5,7 г.)', 'Черноморско злато (Винпром Поморие)', 'grape', 'Поморие', 'Bulgaria', 40, NULL, 'Бренди. ЗГУ, в дъбови бъчви', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Поморийска мускатова', 'Черноморско злато (Винпром Поморие)', 'grape', 'Поморие', 'Bulgaria', 40, NULL, 'Мускатова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Поморийска специална', 'Черноморско злато (Винпром Поморие)', 'grape', 'Поморие', 'Bulgaria', 40, NULL, 'Гроздова ракия отлежала', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Хасковска гроздова', 'Винпром Хасково', 'grape', 'Хасково', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Хасковска мускатова', 'Винпром Хасково', 'grape', 'Хасково', 'Bulgaria', 40, NULL, 'Мускатова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Бренди Хасково', 'Винпром Хасково', 'grape', 'Хасково', 'Bulgaria', 40, NULL, 'Бренди', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Гроздова ракия', 'Винпром Велико Търново', 'grape', 'Велико Търново', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Сливова ракия', 'Винпром Велико Търново', 'plum', 'Велико Търново', 'Bulgaria', 40, NULL, 'Сливова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Ликьори', 'Винпром Велико Търново', 'other', 'Велико Търново', 'Bulgaria', 40, NULL, 'Ликьор', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Оцет', 'Винпром Велико Търново', 'other', 'Велико Търново', 'Bulgaria', 40, NULL, 'Оцет. Странична дейност', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Свищовска гроздова', 'Винпром Свищов', 'grape', 'Свищов', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Свищовска мускатова', 'Винпром Свищов', 'grape', 'Свищов', 'Bulgaria', 40, NULL, 'Мускатова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Гроздови ракии Лясковец', 'Алвиса Винери Партнър', 'grape', 'Лясковец', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Бренди', 'Алвиса Винери Партнър', 'grape', 'Лясковец', 'Bulgaria', 40, NULL, 'Бренди', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Гроздова ракия', 'Винпром Хан Крум', 'grape', 'Търговище', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Мускатова ракия', 'Винпром Хан Крум', 'grape', 'Търговище', 'Bulgaria', 40, NULL, 'Мускатова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Бренди Хан Крум', 'Винпром Хан Крум', 'grape', 'Търговище', 'Bulgaria', 40, NULL, 'Бренди', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Севлиевска гроздова', 'Винпром Севлиево', 'grape', 'Севлиево', 'Bulgaria', 40, NULL, 'Гроздова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Севлиевска сливова', 'Винпром Севлиево', 'plum', 'Севлиево', 'Bulgaria', 40, NULL, 'Сливова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Плодови ракии', 'Винпром Севлиево', 'mixed', 'Севлиево', 'Bulgaria', 40, NULL, 'Плодова ракия', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Soli гроздова ракия', 'Едоардо Миролио', 'grape', 'Сливен', 'Bulgaria', 40, NULL, 'Гроздова ракия. Премиум', 'commercial', true);

INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES ('Ликьори Миролио', 'Едоардо Миролио', 'other', 'Сливен', 'Bulgaria', 40, NULL, 'Ликьор', 'commercial', true);
✓ 109 rows
