/**
 * Converts scripts/rakija-seed.csv → SQL INSERT statements for the rakija table.
 * Run: npx tsx scripts/csv-to-sql.ts > seed.sql
 *
 * CSV columns (in order):
 *   name, producer, fruit, region, country, abv, vintage_year, description, is_verified
 *
 * fruit allowed values: plum | grape | apricot | pear | fig | quince | mixed | other
 * is_verified: true | false  (leave blank → false)
 * country: leave blank → Bulgaria
 * abv: decimal number, e.g. 40 or 43.5  (leave blank → NULL)
 * vintage_year: 4-digit year  (leave blank → NULL)
 */

import fs from "fs";
import path from "path";

const VALID_FRUITS = new Set(["plum", "grape", "apricot", "pear", "fig", "quince", "mixed", "other"]);

const csvPath = path.join(path.dirname(new URL(import.meta.url).pathname), "rakija-seed.csv");
const raw = fs.readFileSync(csvPath, "utf-8").trim().split("\n");

// Skip header row
const rows = raw.slice(1);

const sqls: string[] = [];
const errors: string[] = [];

for (let i = 0; i < rows.length; i++) {
  const line = rows[i].trim();
  if (!line) continue;

  // Simple CSV parse (handles quoted fields with commas inside)
  const cols = parseCsvLine(line);

  const [
    name, producer, fruit, region, country, abvRaw, vintageRaw, description, isVerifiedRaw
  ] = cols.map(c => c.trim());

  const lineNum = i + 2; // +2 = 1-based + header

  if (!name) { errors.push(`Row ${lineNum}: name is required`); continue; }

  if (fruit && !VALID_FRUITS.has(fruit)) {
    errors.push(`Row ${lineNum}: unknown fruit "${fruit}" — allowed: ${[...VALID_FRUITS].join(", ")}`);
    continue;
  }

  const abv = abvRaw ? parseFloat(abvRaw) : null;
  if (abvRaw && isNaN(abv!)) { errors.push(`Row ${lineNum}: invalid abv "${abvRaw}"`); continue; }

  const vintage = vintageRaw ? parseInt(vintageRaw, 10) : null;
  if (vintageRaw && isNaN(vintage!)) { errors.push(`Row ${lineNum}: invalid vintage_year "${vintageRaw}"`); continue; }

  const isVerified = isVerifiedRaw?.toLowerCase() === "true";

  const sql = `INSERT INTO rakija (name, producer, fruit, region, country, abv, vintage_year, description, type, is_verified)
VALUES (${q(name)}, ${q(producer)}, ${q(fruit)}, ${q(region)}, ${q(country || "Bulgaria")}, ${n(abv)}, ${n(vintage)}, ${q(description)}, 'commercial', ${isVerified});`;

  sqls.push(sql);
}

if (errors.length) {
  process.stderr.write("VALIDATION ERRORS:\n" + errors.map(e => "  " + e).join("\n") + "\n");
  process.exit(1);
}

process.stdout.write("-- Generated by csv-to-sql.ts\n\n");
process.stdout.write(sqls.join("\n\n") + "\n");
process.stderr.write(`✓ ${sqls.length} rows\n`);

// ── helpers ────────────────────────────────────────────────────────────────

function q(val: string | undefined): string {
  if (!val) return "NULL";
  return "'" + val.replace(/'/g, "''") + "'";
}

function n(val: number | null): string {
  return val === null ? "NULL" : String(val);
}

function parseCsvLine(line: string): string[] {
  const result: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') { cur += '"'; i++; }
      else inQuotes = !inQuotes;
    } else if (ch === "," && !inQuotes) {
      result.push(cur); cur = "";
    } else {
      cur += ch;
    }
  }
  result.push(cur);
  return result;
}
